export const chartTypesList = [
    {id: 1, name: "Area", selected: false},
    {id: 2, name: "Heatmap", selected: false},
    {id: 3, name: "Horizontal Bar", selected: false},
    {id: 4, name: "Horizontal Box", selected: false},
    {id: 5 , name: "Horizontal Interval", selected: false},
    {id: 6, name: "Line", selected: false},
    {id: 7, name: "Line and Scatter", selected: false},
    {id: 8, name: "Manhattan", selected: false},
    {id: 9, name: "Map", selected: false},
    {id: 10, name: "Other", selected: false},
    {id: 11, name: "Pie", selected: false},
    {id: 12, name: "Scatter", selected: false},
    {id: 13, name: "Surface", selected: false},
    {id: 14, name: "Venn Diagram", selected: false},
    {id: 15, name: "Vertical Bar", selected: false},
    {id: 16, name: "Vertical Box", selected: false},
    {id: 17, name: "Vertical Interval", selected: false},
]